services:
  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
    container_name: bloomia_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8080}
      - API_BASE_URL=http://backend:8080
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
      - DEFAULT_BACKGROUND_COLOR=#fdf8f0
      - DEFAULT_THEME_COLOR=#FF7F50
      - THEME_NAME=coral
      # Firebase Settings (設定が必要)
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
    networks:
      - bloomia_network
    depends_on:
      - backend
    # Remove volume mounts to use built files from Docker image
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules
    #   - /app/.next

    # Backend (Go)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bloomia_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      # Firebase Settings (設定が必要)
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_SERVICE_ACCOUNT_KEY=${FIREBASE_SERVICE_ACCOUNT_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - FRONTEND_URL=${FRONTEND_URL}
      - WEBSOCKET_URL=${WEBSOCKET_URL}
      - RAILWAY_STORAGE_PATH=/app/storage
      - DEFAULT_THEME_COLOR=#FF7F50
      - DEFAULT_BACKGROUND_COLOR=#fdf8f0
      - ENABLE_WHITEBOARD=true
      - ENABLE_NOTES=true
      - ENABLE_GAMIFICATION=true
      - CORAL_THEME_ONLY=true
      # 認証設定（開発環境）
      - DISABLE_AUTH=false
      - MOCK_USER_ROLE=admin
      - MOCK_USER_SCHOOL_ID=1
    networks:
      - bloomia_network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - backend_storage:/app/storage
    # Healthcheck disabled for now - backend is minimal and doesn't include curl/wget
    # healthcheck:
    #   test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

volumes:
  backend_storage:
    driver: local

networks:
  bloomia_network:
    driver: bridge
